name: careplus
description: Mini Project of 2023 to Detect/Predict a person being diabetic or non-diabetic using his medical report. We combine ML model with Flutter App to deliver wonderful UI for lab assistants in order to leverage the power of ML.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  modal_progress_hud_nsn: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png